[project]
name = "outing-guide"
version = "0.1.0"
description = "에버소울 나들이 가이드"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "brotli>=1.1.0",
    "fonttools>=4.59.0",
    "pandas>=2.3.1",
    "requests>=2.32.4",
]
